version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: dragen-docs/source/conf.py  # Path to your Sphinx conf.py

python:
  install:
    - requirements: requirements.txt
